# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       filecase

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    FileCase
Version:    0.4
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  filecase.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Short description of my SailfishOS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build

VENV=.venv-conan-%{_target_cpu}
export TARGET_CPU="%{_target_cpu}"
export SAILFISHCONNECT_PACKAGE_VERSION="%{version}-%{release}"

SOURCE_DIR=`readlink -f %{_sourcedir}/..`

if [ "$TARGET_CPU" == "i486" ] ; then  
  GENERATOR="Unix Makefiles"
else
  GENERATOR="Ninja"
fi

if [ "$SAILFISH_SDK_FRONTEND" == "qtcreator" ] ; then  
  CMAKE_BUILD_TYPE="Debug"
else
  CMAKE_BUILD_TYPE="RelWithDebInfo"
fi

if [ -f "CMakeLists.txt" ] ; then
  BUILD_DIR="rpmbuilddir-%{_target_cpu}"
else 
  BUILD_DIR="."
fi
export CONAN_USER_HOME=${SOURCE_DIR}

# install virtualenv
if [ ! -f ~/.local/bin/virtualenv ] ; then
  python3 -m pip install --no-warn-script-location --user virtualenv
fi

# create virtualenv and install conan
if [ ! -f "$VENV/bin/conan" ] ; then
  ~/.local/bin/virtualenv --python=python3 "$VENV"
  source "$VENV/bin/activate"
  pip install conan
else
  source "$VENV/bin/activate"
fi

# speed up conan remote add
if ! grep -sq sailfishos "$CONAN_USER_HOME/.conan/remotes.json" ; then
  conan remote add -f sailfishos https://gitlab.com/api/v4/projects/12208535/packages/conan
fi

mkdir -p "$BUILD_DIR"

cd "$BUILD_DIR"
conan install "$SOURCE_DIR" --build=missing --profile="$SOURCE_DIR/dev/profiles/%{_target_cpu}"
conan remove -f "*" --builds --src --system-reqs

cmake \
  -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCONAN_DISABLE_CHECK_COMPILER=ON \
  -DSAILFISHOS=ON \
  -G "$GENERATOR" \
  "$SOURCE_DIR"

cmake --build . -- %{?_smp_mflags}

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files
